server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "https://eureka7002.com:7002/eureka/,https://eureka7003.com:7003/eureka/"

