server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com #eureka服务端实例名称
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: https://eureka7001.com:7001/eureka/,https://eureka7002.com:7002/eureka/