server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  redis:
    database: 0
    timeout: 1000           # 连接超时时间（毫秒）
    host: 192.168.88.128        # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: root              # Redis服务器连接密码（默认为空）
    lettuce:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: after_route
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            #            - Path=/payment/discovery   # 路径匹配
            #            - Query=token, abc.         #查询参数匹配,可以匹配正则表达式
            - Method=GET       #亲求方法匹配



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka"
