server:
  port: 8801

spring:
  application:
    name: cloud-stream-rabbitmq-provide8801
  cloud:
    stream:
      binders:
        defaultRabbit: #表示定义名，与binding整合
           type: rabbit #消息组件类型
           environment:
             spring:
               rabbitmq:
                 host: 192.168.88.123
                 port: 5672
                 username: guest
                 password: guest
      bindings:
        output: #一个通道名字
          destination: studyExchange #自定义交换机名称
          content-type: application/json
          binder: defaultRabbit



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://eureka7001.com:7001/eureka"
  instance:
    instance-id: cloud-stream-rabbitmq-provide8801
    prefer-ip-address: true