server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端实例名称
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: "https://eureka7001.com:7001/eureka/,https://eureka7003.com:7003/eureka/"